<br>
<br>


## Current Research Interests

<br>
<br>
I am currently interested in issues regarding student mental health. Specifically, on-campus mental health services which aim to provide early intervention with the goal of improving access to counselling services.
<br>
<br>

**Ongoing Research Projects** <br>

Title: Evaluating User and Supporter Experiences of a Student-Led Peer Support Service <br>
The aim of this project is to evaluate the University of Glasgow's [CaPS Peer Support service](https://www.gla.ac.uk/myglasgow/counselling/peersupport/). The student-led service provides information and support for students with mild mental health issues. I will be involved in the initial stages of a mixed-method investigation to collect the experiences of those involved with the service, and use this to facilitate and inform the upcoming expansion of the program.


**Systematic Review** <br>

I will also be assisting [Jelena Milicev](http://www.psy.gla.ac.uk/staff/?id=JM010) in writing a systematic review on the prevalence of mental health issues in postrgraduate students.
