---
title: "Alexandra Meikle"
---

I am a postgraduate student in the University of Glasgow's
[Institute of Neuroscience and Psychology](http://www.gla.ac.uk/researchinstitutes/neurosciencepsychology/). I graduated from the University of Glasgow in 2018 with an M.A. in Psychology (with Honours of the First Class). I am currently working towards an M.Sc. in Research Methods of Psychological Science, working on a project with [Professor Stephany Biello](https://www.gla.ac.uk/schools/psychology/staff/stephanybiello/).


### Contact Info
    Room 101
    58 Hillhead Street
    Glasgow
    G12 8QB
    Telephone	+44 (0)141 330 ----
    Email 2133759m@student.gla.ac.uk


## Research Interests

### Student Mental Health

I am currently involved in a project evaluating the Peer Support service ran within the University of Glasgow's Counselling and Psychological services. The student-led service aims to provide support for peers with mild mental health issues. I will be involved in the initial stages of a mixed-method investigation to collect the experiences of those involved with the service, and use this to facilitate and inform the upcoming expansion of the program.

### Sleep and Circadian Timing

For my final year prohject I conducted an experiment examining the effect of exposure to dim light at night on the activity-rest cycles of mice. 