<br>
<br>

## Experience 

<br>
<br>

**Strengthening Circadian Rhythmicity in Mice Housed Under Dim Light at Night Through 3-HR Dark Pulses (2018)**
<br>
*Final Year Undergraduate Project*<br>
     Abstract: Timing cues for the circadian clock are diminished by artificial dim light at night in the home and
urbanised environment; subsequently effecting the rhythmicity of sleeping patterns. Animal research
has already shown that the presence of a dark pulse can act as a zeitgeber and improve
synchronisation under the traditional light/dark cycle. The present study aims to examine the effect of
dark pulses on mice housed under DLAN. A cross-sectional, counterbalanced mixed design was used
to observe 4 days of 3-hour pulses on behavioural rhythms in male mice (n=23) exposed to a 12:12,
DLAN schedule. The presence of a dark pulse significantly increased interdaily stability and
decreased intradaily variability, and the magnitude of the effect on IV was stronger in young mice (3-
4 months) than in old (13-15 months); indicating a reduction in responsivity in the older group. The
findings presented here exhibit an effective method for strengthening circadian rhythmicity in mice
housed in DLAN, with potentially long-lasting effects on stability. 
<br>
<br>
<br>
**Research Studentship: Glasgow Science Centre (2017)**
     I conducted a summer research project on sleep and reasoning biases, supervised by Prof. Stephany Biello. We used a modified "beads task" to investigate the relationship between sleep disruption and jumping to conclusions bias, and collected data from visitors at the GSC. Data was collected at a 'Meet the Expert' public engagement stall.

